version: "3.7"

services:
    app:
        build:
            args:
                user: guilherme
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: tarefas
        container_name: tarefas-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tarefas

    redis:
        image: redis:latest
        container_name: tarefas-redis
        restart: unless-stopped
        networks:
            - tarefas

    db:
        image: postgres:15.2
        container_name: tarefas-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5432:5432'
        networks:
            - tarefas

    nginx:
        image: nginx:1.22.1-alpine
        container_name: tarefas-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - tarefas

    rabbitmq:
        image: rabbitmq:3.11.10-management
        container_name: tarefas-rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        user: 1000:1000
        volumes:
            - './docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
            - './docker/rabbitmq/log/:/var/log/rabbitmq'
        networks:
            - tarefas

networks:
    tarefas:
        name: tarefas
        driver: bridge
