version: "3.7"

services:
    app:
        build:
            args:
                user: guilherme
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: tarefas
        container_name: tarefas-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tarefas

    redis:
        image: redis:latest
        container_name: tarefas-redis
        restart: unless-stopped
        networks:
            - tarefas

    db:
        image: postgres:15.2
        container_name: tarefas-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - tarefas

    nginx:
        image: nginx:1.22.1-alpine
        container_name: tarefas-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - tarefas

networks:
    tarefas:
        driver: bridge
